# Generated by Django 3.0.3 on 2020-03-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='departure',
        ),
    ]
