# Generated by Django 3.0.3 on 2020-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200303_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='endTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='startTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
