# Generated by Django 3.0.3 on 2020-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200306_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
