# Generated by Django 3.0.3 on 2020-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200306_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='stops',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
