# Generated by Django 3.0.3 on 2020-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=30, null=True)),
                ('retAirline', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('retDate', models.CharField(max_length=10, null=True)),
                ('startTime', models.CharField(max_length=10, null=True)),
                ('endTime', models.CharField(max_length=10, null=True)),
                ('retStartTime', models.CharField(max_length=10, null=True)),
                ('retEndTime', models.CharField(max_length=10, null=True)),
                ('stops', models.CharField(max_length=30, null=True)),
                ('retStops', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(max_length=10),
        ),
    ]
