# Generated by Django 3.0.3 on 2020-04-07 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservedflights', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedflight',
            name='dropabale',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedflight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
