# Generated by Django 3.0.3 on 2020-04-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservedflights', '0004_auto_20200407_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedflight',
            name='stops',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
