# Generated by Django 3.0.3 on 2020-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservedflights', '0005_reservedflight_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedflight',
            name='dropable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
