# Generated by Django 3.0.3 on 2020-04-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservedflights', '0006_auto_20200416_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedReturnFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=10)),
                ('airline', models.CharField(max_length=30, null=True)),
                ('retAirline', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('retDate', models.CharField(max_length=10, null=True)),
                ('startTime', models.CharField(max_length=10, null=True)),
                ('endTime', models.CharField(max_length=10, null=True)),
                ('retStartTime', models.CharField(max_length=10, null=True)),
                ('retEndTime', models.CharField(max_length=10, null=True)),
                ('stops', models.CharField(max_length=30, null=True)),
                ('retStops', models.CharField(max_length=30, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('dropable', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
