# Generated by Django 3.0.3 on 2020-04-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservedflights', '0007_reservedreturnflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfAdults', models.SmallIntegerField()),
                ('noOfChildren', models.SmallIntegerField()),
                ('dateTime', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.FloatField()),
                ('reservedFlightNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservedflights.ReservedReturnFlight')),
            ],
        ),
    ]
